version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: go-sql-auth
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: amine143
      MYSQL_DATABASE: Qore2024DB
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
